# Generated by Django 5.0.2 on 2024-02-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('slug', models.SlugField(max_length=255, primary_key=True, serialize=False, verbose_name='slug')),
                ('title', models.TextField(unique=True, verbose_name='title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('author', models.CharField(max_length=127, verbose_name='author')),
                ('content', models.TextField(verbose_name='content')),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
            },
        ),
    ]
