# Generated by Django 5.0.2 on 2024-02-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'article', 'verbose_name_plural': 'articles'},
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='This field is autocreated.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='-', help_text='This field is autocreated.', max_length=255, primary_key=True, serialize=False, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(help_text='Title must be unique', unique=True, verbose_name='title'),
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.SlugField(default='autocreate', max_length=63, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=63)),
                ('articles', models.ManyToManyField(blank=True, to='article.article')),
            ],
        ),
    ]
