# Generated by Django 5.0.2 on 2024-02-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_articlecategory_articles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecategory',
            name='description',
            field=models.TextField(blank=True, max_length=511, null=True),
        ),
    ]
