# Generated by Django 5.0.2 on 2024-02-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_articlecategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecategory',
            name='count_articles',
            field=models.IntegerField(default=0, verbose_name='count article'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='articles',
            field=models.ManyToManyField(blank=True, to='article.article'),
        ),
    ]
