# Generated by Django 5.0.2 on 2024-02-20 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_articlecategory_count_articles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecategory',
            name='count_articles',
        ),
    ]
